import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className=" h-screen flex flex-row justify-start">
            <Sidebar></Sidebar>
            <section className="flex-1 p-4">{children}</section>
          </main>
        </Providers>
      </body>
    </html>
  );
}
